apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubewise-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: kubewise-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
